### ISSUE TITLE
Anrop till url:en */users* utan att vara inloggad.

### ISSUE THREAD

**Issue by SvanteArvedson** [mf222nb/1DV450_Laboration_1#4]
Om man gör ett anrop till url:en _/users_ utan att vara inloggad visas en tom sida upp. Ett bättre beteende skulle vara att redirecta användaren till inloggningssidan.

**Comment by mf222nb** [comment]
Jag har fixat detta nu med en felsida så kommer upp om man försöker anropa den url:en utan att vara inloggad.
