### ISSUE TITLE
Klick på länken BACK som inloggad admin.

### ISSUE THREAD

**Issue by SvanteArvedson** [mf222nb/1DV450_Laboration_1#6]
Om man som inloggad admin klickar på länken **Back** så loggas man ut ur applikationen och återvänder till login-formuläret. Oväntat beteende för en länk som heter **Back**.

**Comment by mf222nb** [comment]
Jag har ingen länk som heter back när man är inloggad som Admin, den länken kommer bara om det har inträffat något fel och är en sida jag visar för de flesta felen därför som den går till login-formuläret.
