### ISSUE TITLE
Admin kan inte radera användarkonton

### ISSUE THREAD

**Issue by SvanteArvedson** [mf222nb/1DV450_Laboration_1#8]
Admin kan inte radera användarkonton via det grafiska gränssnittet. Visserligen inte ett krav för uppgiften men en tämligen funktion att lägga till och en funktionalitet som hör till ett Admin-gränssnitt.

**Comment by SvanteArvedson** [comment]
Jag lägger märke till att vyerna har kod för att erbjuda admin en möjlighet att radera användare. Tror att felet beror på att controllern inte raderar gamla poster i tabellen **Keys** utan bara sätter attributet **user_id** till **nil**.

**Comment by mf222nb** [comment]
En admin kan inte radera konton men admin kan radera nycklar
