### ISSUE TITLE
Test Should_not_save_without_name i User_test

### ISSUE THREAD

**Issue by SvanteArvedson** [mf222nb/1DV450_Laboration_1#9]
Testet Should_not_save_without_name i filen user_test.rb slänger ett error på rad 10. Ser dock inte vad det kan bero på. Test är visserligen inte ett krav för uppgiften så det borde inte göra så mycket.

**Comment by mf222nb** [comment]
Tester har jag inte lagt ner någon tid på utan det är något jag tog från en guide men inget som jag teskörde så att den inte fungerar förvånar mig inte.
